name: Build JAR
on:
  workflow_dispatch:
  push:
    branches: [ '1.17' ]
    paths:
      - 'build.gradle'
  pull_request:
    branches: [ '1.17' ]
    paths:
      - 'src/**'
      - 'build.gradle'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon --max-workers 1

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Generated JAR
          path: build/libs/
